name: grocery_delivery
description: A Flutter app for grocery delivery
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.2 <4.0.0"
  flutter: ^3.27.4

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  cubit_form: ^2.0.5
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^8.1.1
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  shimmer: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: SF UI Display
      fonts:
        - asset: assets_common/fonts/SanFrancisco/SFProDisplay-Ultralight.ttf
          weight: 100
        - asset: assets_common/fonts/SanFrancisco/SFProDisplay-Thin.ttf
          weight: 200
        - asset: assets_common/fonts/SanFrancisco/SFProDisplay-Light.ttf
          weight: 300
        - asset: assets_common/fonts/SanFrancisco/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets_common/fonts/SanFrancisco/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets_common/fonts/SanFrancisco/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets_common/fonts/SanFrancisco/SFProDisplay-Bold.ttf
          weight: 700
        - asset: assets_common/fonts/SanFrancisco/SFProDisplay-Heavy.ttf
          weight: 800
        - asset: assets_common/fonts/SanFrancisco/SFProDisplay-Black.ttf
          weight: 900
    - family: SF UI Text
      fonts:
        - asset: assets_common/fonts/SanFrancisco/SFProText-Light.ttf
          weight: 300
        - asset: assets_common/fonts/SanFrancisco/SFProText-Regular.ttf
          weight: 400
        - asset: assets_common/fonts/SanFrancisco/SFProText-Medium.ttf
          weight: 500
        - asset: assets_common/fonts/SanFrancisco/SFProText-Semibold.ttf
          weight: 600
        - asset: assets_common/fonts/SanFrancisco/SFProText-Bold.ttf
          weight: 700